version: '3.8'

services:
  wgeasy:
    networks:
      - proxy
    environment:
      # ⚠️ Required:
      - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG
      - PORT=51821
      - WG_PORT=51820
      - WG_HOST=IPADDRESS
      - LANG=ru
      - WG_PERSISTENT_KEEPALIVE=10
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_ADDRESS_RANGE=24
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_MTU=1420
      - UI_TRAFFIC_STATS=true
    image: ghcr.io/wg-easy/wg-easy
    container_name: wgeasy
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wgeasy.rule=Host(`IPADDRESS`)"
      - "traefik.http.routers.wgeasy.entrypoints=websecure"
      - "traefik.http.routers.wgeasy.tls=true"
      - "traefik.http.routers.wgeasy.tls.certresolver=myresolver"
      - "traefik.http.services.wgeasy.loadbalancer.server.port=51821"

  xui:
    image: alireza7/x-ui:latest
    container_name: xui
    hostname: IPADDRESS
    volumes:
      - ./x-ui/:/etc/x-ui/
      - ./letsencrypt:/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Novosibirsk
      XRAY_VMESS_AEAD_FORCED: false
    tty: true
    network_mode: host
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xui.rule=Host(`IPADDRESS`) && PathPrefix(`/`)"
      - "traefik.http.routers.xui.entrypoints=websecure"
      - "traefik.http.routers.xui.tls=true"
      - "traefik.http.routers.xui.tls.certresolver=myresolver"
      - "traefik.http.services.xui.loadbalancer.server.port=54321"

  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      - proxy
    command:
      - --log.level=INFO
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.email=admin@IPADDRESS
    ports:
      - "80:80"
      #- "443:443"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`IPADDRESS`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG"

  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`IPADDRESS`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

networks:
  proxy:
    name: proxy
    external: true
